#!/bin/bash
function join_by { local IFS="$1"; shift; echo "$*"; }

ERRORS=()

# usage: ci_run echo 1; or ci_run false
function ci_run() {
    # hopefully 60 minutes is enought for anything?
    if [[ -v CRON ]]; then
        where="/dev/null"
    else
        where="/dev/stdout"
    fi
    if ! timeout 3600 "$@" >$where ; then
        joined=$(join_by "_" "$@") # ugh..
        ERRORS+=($joined)
    fi
}

# usage: ci_report_errors as the last line of your script
function ci_report_errors() {
    nerrors="${#ERRORS[@]}"
    if [[ $nerrors -eq 0 ]]; then
        echo "No errors"
    else
        echo "ERRORS in:"
        for e in ${ERRORS[*]}; do
            echo "$e"
        done
        exit 1
    fi
}
