#!/usr/bin/env python3
from subprocess import check_output, check_call

def yesno(prompt: str) -> bool:
    import sys
    sys.stdout.write(prompt + " ")
    sys.stdout.flush()
    while True:
        r = check_output(['bash', '-c', 'read -n 1 && echo $REPLY']).decode('utf8').strip().lower()
        if r == 'y':
            return True
        if r == 'n':
            return False
        print("Please respond y/n")

def iter_gone():
    out = check_output('git branch -vv', shell=True).decode('utf-8').splitlines()
    for l in out:
        if 'gone]' in l:
            l = l.strip()
            bname = l.split()[0]
            rest = l[len(bname):].strip()
            yield (bname, rest)

for name, rest in iter_gone():
    if yesno("Delete {} {}?".format(name, rest)):
        print()
        check_call(['git', 'branch', '-d', name])
    else:
        print("  keeping " + name)

