#!/bin/bash
perl \
    -pe 's/\x1b\[91m/\${color red}/g;' \
    -pe 's/\x1b\[92m/\${color green}/g;' \
    -pe 's/\x1b\[93m/\${color orange}/g;' \
    -pe 's/\x1b\[94m/\${color blue}/g;' \
    -pe 's/\x1b\[0m/\${color}/g;'
